USE freedb_boxify;

CREATE TABLE Users (
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
name VARCHAR(45) NOT NULL,
`user` VARCHAR(45) NOT NULL,
email VARCHAR(45) NOT NULL,
`password` VARCHAR(255) NOT NULL
);

CREATE TABLE Box (
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
tittle VARCHAR(45) NOT NULL,
objects JSON NOT NULL,
fk_user_id INT,
    FOREIGN KEY (fk_user_id) REFERENCES Users(id)
);

